/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WisdomIndexRouteImport } from './routes/wisdom.index'
import { Route as ServeIndexRouteImport } from './routes/serve.index'
import { Route as NextStepsIndexRouteImport } from './routes/next-steps.index'
import { Route as MyJourneyIndexRouteImport } from './routes/my-journey.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WisdomLordRouteImport } from './routes/wisdom.lord'
import { Route as WisdomAudioPlaylistsRouteImport } from './routes/wisdom.audio-playlists'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as ServeVolunteerRouteImport } from './routes/serve.volunteer'
import { Route as ServeTransformationalStoriesRouteImport } from './routes/serve.transformational-stories'
import { Route as ServeServantLeadersRouteImport } from './routes/serve.servant-leaders'
import { Route as ServeGiveRouteImport } from './routes/serve.give'
import { Route as PreviewSlugRouteImport } from './routes/preview.$slug'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as NextStepsSpiritualRetreatRouteImport } from './routes/next-steps.spiritual-retreat'
import { Route as NextStepsSmallGroupsRouteImport } from './routes/next-steps.small-groups'
import { Route as NextStepsOtherProjectsRouteImport } from './routes/next-steps.other-projects'
import { Route as NextStepsAskRouteImport } from './routes/next-steps.ask'
import { Route as MyJourneyMyStoryRouteImport } from './routes/my-journey.my-story'
import { Route as MyJourneyMyGuruRouteImport } from './routes/my-journey.my-guru'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as WisdomBlog2IndexRouteImport } from './routes/wisdom.blog2.index'
import { Route as WisdomBlog1IndexRouteImport } from './routes/wisdom.blog1.index'
import { Route as WisdomBlogIndexRouteImport } from './routes/wisdom.blog.index'
import { Route as WisdomBlog2SlugRouteImport } from './routes/wisdom.blog2.$slug'
import { Route as WisdomBlog1SlugRouteImport } from './routes/wisdom.blog1.$slug'
import { Route as WisdomBlogSlugRouteImport } from './routes/wisdom.blog.$slug'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'
import { Route as AdminDesignIdRouteImport } from './routes/admin.design.$id'

const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomIndexRoute = WisdomIndexRouteImport.update({
  id: '/wisdom/',
  path: '/wisdom/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeIndexRoute = ServeIndexRouteImport.update({
  id: '/serve/',
  path: '/serve/',
  getParentRoute: () => rootRouteImport,
} as any)
const NextStepsIndexRoute = NextStepsIndexRouteImport.update({
  id: '/next-steps/',
  path: '/next-steps/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJourneyIndexRoute = MyJourneyIndexRouteImport.update({
  id: '/my-journey/',
  path: '/my-journey/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WisdomLordRoute = WisdomLordRouteImport.update({
  id: '/wisdom/lord',
  path: '/wisdom/lord',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomAudioPlaylistsRoute = WisdomAudioPlaylistsRouteImport.update({
  id: '/wisdom/audio-playlists',
  path: '/wisdom/audio-playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeVolunteerRoute = ServeVolunteerRouteImport.update({
  id: '/serve/volunteer',
  path: '/serve/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeTransformationalStoriesRoute =
  ServeTransformationalStoriesRouteImport.update({
    id: '/serve/transformational-stories',
    path: '/serve/transformational-stories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServeServantLeadersRoute = ServeServantLeadersRouteImport.update({
  id: '/serve/servant-leaders',
  path: '/serve/servant-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeGiveRoute = ServeGiveRouteImport.update({
  id: '/serve/give',
  path: '/serve/give',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSlugRoute = PreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NextStepsSpiritualRetreatRoute =
  NextStepsSpiritualRetreatRouteImport.update({
    id: '/next-steps/spiritual-retreat',
    path: '/next-steps/spiritual-retreat',
    getParentRoute: () => rootRouteImport,
  } as any)
const NextStepsSmallGroupsRoute = NextStepsSmallGroupsRouteImport.update({
  id: '/next-steps/small-groups',
  path: '/next-steps/small-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const NextStepsOtherProjectsRoute = NextStepsOtherProjectsRouteImport.update({
  id: '/next-steps/other-projects',
  path: '/next-steps/other-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NextStepsAskRoute = NextStepsAskRouteImport.update({
  id: '/next-steps/ask',
  path: '/next-steps/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJourneyMyStoryRoute = MyJourneyMyStoryRouteImport.update({
  id: '/my-journey/my-story',
  path: '/my-journey/my-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJourneyMyGuruRoute = MyJourneyMyGuruRouteImport.update({
  id: '/my-journey/my-guru',
  path: '/my-journey/my-guru',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const WisdomBlog2IndexRoute = WisdomBlog2IndexRouteImport.update({
  id: '/wisdom/blog2/',
  path: '/wisdom/blog2/',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomBlog1IndexRoute = WisdomBlog1IndexRouteImport.update({
  id: '/wisdom/blog1/',
  path: '/wisdom/blog1/',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomBlogIndexRoute = WisdomBlogIndexRouteImport.update({
  id: '/wisdom/blog/',
  path: '/wisdom/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomBlog2SlugRoute = WisdomBlog2SlugRouteImport.update({
  id: '/wisdom/blog2/$slug',
  path: '/wisdom/blog2/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomBlog1SlugRoute = WisdomBlog1SlugRouteImport.update({
  id: '/wisdom/blog1/$slug',
  path: '/wisdom/blog1/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomBlogSlugRoute = WisdomBlogSlugRouteImport.update({
  id: '/wisdom/blog/$slug',
  path: '/wisdom/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignIdRoute = AdminDesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/surprise': typeof SurpriseRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/my-journey/my-guru': typeof MyJourneyMyGuruRoute
  '/my-journey/my-story': typeof MyJourneyMyStoryRoute
  '/next-steps/ask': typeof NextStepsAskRoute
  '/next-steps/other-projects': typeof NextStepsOtherProjectsRoute
  '/next-steps/small-groups': typeof NextStepsSmallGroupsRoute
  '/next-steps/spiritual-retreat': typeof NextStepsSpiritualRetreatRoute
  '/post/$slug': typeof PostSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/serve/give': typeof ServeGiveRoute
  '/serve/servant-leaders': typeof ServeServantLeadersRoute
  '/serve/transformational-stories': typeof ServeTransformationalStoriesRoute
  '/serve/volunteer': typeof ServeVolunteerRoute
  '/tag/$slug': typeof TagSlugRoute
  '/wisdom/audio-playlists': typeof WisdomAudioPlaylistsRoute
  '/wisdom/lord': typeof WisdomLordRoute
  '/admin/': typeof AdminIndexRoute
  '/my-journey/': typeof MyJourneyIndexRoute
  '/next-steps/': typeof NextStepsIndexRoute
  '/serve/': typeof ServeIndexRoute
  '/wisdom/': typeof WisdomIndexRoute
  '/admin/design/$id': typeof AdminDesignIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/wisdom/blog/$slug': typeof WisdomBlogSlugRoute
  '/wisdom/blog1/$slug': typeof WisdomBlog1SlugRoute
  '/wisdom/blog2/$slug': typeof WisdomBlog2SlugRoute
  '/wisdom/blog/': typeof WisdomBlogIndexRoute
  '/wisdom/blog1/': typeof WisdomBlog1IndexRoute
  '/wisdom/blog2/': typeof WisdomBlog2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/surprise': typeof SurpriseRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/my-journey/my-guru': typeof MyJourneyMyGuruRoute
  '/my-journey/my-story': typeof MyJourneyMyStoryRoute
  '/next-steps/ask': typeof NextStepsAskRoute
  '/next-steps/other-projects': typeof NextStepsOtherProjectsRoute
  '/next-steps/small-groups': typeof NextStepsSmallGroupsRoute
  '/next-steps/spiritual-retreat': typeof NextStepsSpiritualRetreatRoute
  '/post/$slug': typeof PostSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/serve/give': typeof ServeGiveRoute
  '/serve/servant-leaders': typeof ServeServantLeadersRoute
  '/serve/transformational-stories': typeof ServeTransformationalStoriesRoute
  '/serve/volunteer': typeof ServeVolunteerRoute
  '/tag/$slug': typeof TagSlugRoute
  '/wisdom/audio-playlists': typeof WisdomAudioPlaylistsRoute
  '/wisdom/lord': typeof WisdomLordRoute
  '/admin': typeof AdminIndexRoute
  '/my-journey': typeof MyJourneyIndexRoute
  '/next-steps': typeof NextStepsIndexRoute
  '/serve': typeof ServeIndexRoute
  '/wisdom': typeof WisdomIndexRoute
  '/admin/design/$id': typeof AdminDesignIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/wisdom/blog/$slug': typeof WisdomBlogSlugRoute
  '/wisdom/blog1/$slug': typeof WisdomBlog1SlugRoute
  '/wisdom/blog2/$slug': typeof WisdomBlog2SlugRoute
  '/wisdom/blog': typeof WisdomBlogIndexRoute
  '/wisdom/blog1': typeof WisdomBlog1IndexRoute
  '/wisdom/blog2': typeof WisdomBlog2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/home': typeof HomeRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/surprise': typeof SurpriseRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/my-journey/my-guru': typeof MyJourneyMyGuruRoute
  '/my-journey/my-story': typeof MyJourneyMyStoryRoute
  '/next-steps/ask': typeof NextStepsAskRoute
  '/next-steps/other-projects': typeof NextStepsOtherProjectsRoute
  '/next-steps/small-groups': typeof NextStepsSmallGroupsRoute
  '/next-steps/spiritual-retreat': typeof NextStepsSpiritualRetreatRoute
  '/post/$slug': typeof PostSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/serve/give': typeof ServeGiveRoute
  '/serve/servant-leaders': typeof ServeServantLeadersRoute
  '/serve/transformational-stories': typeof ServeTransformationalStoriesRoute
  '/serve/volunteer': typeof ServeVolunteerRoute
  '/tag/$slug': typeof TagSlugRoute
  '/wisdom/audio-playlists': typeof WisdomAudioPlaylistsRoute
  '/wisdom/lord': typeof WisdomLordRoute
  '/admin/': typeof AdminIndexRoute
  '/my-journey/': typeof MyJourneyIndexRoute
  '/next-steps/': typeof NextStepsIndexRoute
  '/serve/': typeof ServeIndexRoute
  '/wisdom/': typeof WisdomIndexRoute
  '/admin/design/$id': typeof AdminDesignIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/wisdom/blog/$slug': typeof WisdomBlogSlugRoute
  '/wisdom/blog1/$slug': typeof WisdomBlog1SlugRoute
  '/wisdom/blog2/$slug': typeof WisdomBlog2SlugRoute
  '/wisdom/blog/': typeof WisdomBlogIndexRoute
  '/wisdom/blog1/': typeof WisdomBlog1IndexRoute
  '/wisdom/blog2/': typeof WisdomBlog2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/events'
    | '/home'
    | '/newsletter'
    | '/rss.xml'
    | '/surprise'
    | '/admin/login'
    | '/admin/new'
    | '/admin/setup'
    | '/my-journey/my-guru'
    | '/my-journey/my-story'
    | '/next-steps/ask'
    | '/next-steps/other-projects'
    | '/next-steps/small-groups'
    | '/next-steps/spiritual-retreat'
    | '/post/$slug'
    | '/preview/$slug'
    | '/serve/give'
    | '/serve/servant-leaders'
    | '/serve/transformational-stories'
    | '/serve/volunteer'
    | '/tag/$slug'
    | '/wisdom/audio-playlists'
    | '/wisdom/lord'
    | '/admin/'
    | '/my-journey/'
    | '/next-steps/'
    | '/serve/'
    | '/wisdom/'
    | '/admin/design/$id'
    | '/admin/edit/$id'
    | '/wisdom/blog/$slug'
    | '/wisdom/blog1/$slug'
    | '/wisdom/blog2/$slug'
    | '/wisdom/blog/'
    | '/wisdom/blog1/'
    | '/wisdom/blog2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/events'
    | '/home'
    | '/newsletter'
    | '/rss.xml'
    | '/surprise'
    | '/admin/login'
    | '/admin/new'
    | '/admin/setup'
    | '/my-journey/my-guru'
    | '/my-journey/my-story'
    | '/next-steps/ask'
    | '/next-steps/other-projects'
    | '/next-steps/small-groups'
    | '/next-steps/spiritual-retreat'
    | '/post/$slug'
    | '/preview/$slug'
    | '/serve/give'
    | '/serve/servant-leaders'
    | '/serve/transformational-stories'
    | '/serve/volunteer'
    | '/tag/$slug'
    | '/wisdom/audio-playlists'
    | '/wisdom/lord'
    | '/admin'
    | '/my-journey'
    | '/next-steps'
    | '/serve'
    | '/wisdom'
    | '/admin/design/$id'
    | '/admin/edit/$id'
    | '/wisdom/blog/$slug'
    | '/wisdom/blog1/$slug'
    | '/wisdom/blog2/$slug'
    | '/wisdom/blog'
    | '/wisdom/blog1'
    | '/wisdom/blog2'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/events'
    | '/home'
    | '/newsletter'
    | '/rss.xml'
    | '/surprise'
    | '/admin/login'
    | '/admin/new'
    | '/admin/setup'
    | '/my-journey/my-guru'
    | '/my-journey/my-story'
    | '/next-steps/ask'
    | '/next-steps/other-projects'
    | '/next-steps/small-groups'
    | '/next-steps/spiritual-retreat'
    | '/post/$slug'
    | '/preview/$slug'
    | '/serve/give'
    | '/serve/servant-leaders'
    | '/serve/transformational-stories'
    | '/serve/volunteer'
    | '/tag/$slug'
    | '/wisdom/audio-playlists'
    | '/wisdom/lord'
    | '/admin/'
    | '/my-journey/'
    | '/next-steps/'
    | '/serve/'
    | '/wisdom/'
    | '/admin/design/$id'
    | '/admin/edit/$id'
    | '/wisdom/blog/$slug'
    | '/wisdom/blog1/$slug'
    | '/wisdom/blog2/$slug'
    | '/wisdom/blog/'
    | '/wisdom/blog1/'
    | '/wisdom/blog2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  HomeRoute: typeof HomeRoute
  NewsletterRoute: typeof NewsletterRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SurpriseRoute: typeof SurpriseRoute
  MyJourneyMyGuruRoute: typeof MyJourneyMyGuruRoute
  MyJourneyMyStoryRoute: typeof MyJourneyMyStoryRoute
  NextStepsAskRoute: typeof NextStepsAskRoute
  NextStepsOtherProjectsRoute: typeof NextStepsOtherProjectsRoute
  NextStepsSmallGroupsRoute: typeof NextStepsSmallGroupsRoute
  NextStepsSpiritualRetreatRoute: typeof NextStepsSpiritualRetreatRoute
  PostSlugRoute: typeof PostSlugRoute
  PreviewSlugRoute: typeof PreviewSlugRoute
  ServeGiveRoute: typeof ServeGiveRoute
  ServeServantLeadersRoute: typeof ServeServantLeadersRoute
  ServeTransformationalStoriesRoute: typeof ServeTransformationalStoriesRoute
  ServeVolunteerRoute: typeof ServeVolunteerRoute
  TagSlugRoute: typeof TagSlugRoute
  WisdomAudioPlaylistsRoute: typeof WisdomAudioPlaylistsRoute
  WisdomLordRoute: typeof WisdomLordRoute
  MyJourneyIndexRoute: typeof MyJourneyIndexRoute
  NextStepsIndexRoute: typeof NextStepsIndexRoute
  ServeIndexRoute: typeof ServeIndexRoute
  WisdomIndexRoute: typeof WisdomIndexRoute
  WisdomBlogSlugRoute: typeof WisdomBlogSlugRoute
  WisdomBlog1SlugRoute: typeof WisdomBlog1SlugRoute
  WisdomBlog2SlugRoute: typeof WisdomBlog2SlugRoute
  WisdomBlogIndexRoute: typeof WisdomBlogIndexRoute
  WisdomBlog1IndexRoute: typeof WisdomBlog1IndexRoute
  WisdomBlog2IndexRoute: typeof WisdomBlog2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom/': {
      id: '/wisdom/'
      path: '/wisdom'
      fullPath: '/wisdom/'
      preLoaderRoute: typeof WisdomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve/': {
      id: '/serve/'
      path: '/serve'
      fullPath: '/serve/'
      preLoaderRoute: typeof ServeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-steps/': {
      id: '/next-steps/'
      path: '/next-steps'
      fullPath: '/next-steps/'
      preLoaderRoute: typeof NextStepsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-journey/': {
      id: '/my-journey/'
      path: '/my-journey'
      fullPath: '/my-journey/'
      preLoaderRoute: typeof MyJourneyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wisdom/lord': {
      id: '/wisdom/lord'
      path: '/wisdom/lord'
      fullPath: '/wisdom/lord'
      preLoaderRoute: typeof WisdomLordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom/audio-playlists': {
      id: '/wisdom/audio-playlists'
      path: '/wisdom/audio-playlists'
      fullPath: '/wisdom/audio-playlists'
      preLoaderRoute: typeof WisdomAudioPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve/volunteer': {
      id: '/serve/volunteer'
      path: '/serve/volunteer'
      fullPath: '/serve/volunteer'
      preLoaderRoute: typeof ServeVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve/transformational-stories': {
      id: '/serve/transformational-stories'
      path: '/serve/transformational-stories'
      fullPath: '/serve/transformational-stories'
      preLoaderRoute: typeof ServeTransformationalStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve/servant-leaders': {
      id: '/serve/servant-leaders'
      path: '/serve/servant-leaders'
      fullPath: '/serve/servant-leaders'
      preLoaderRoute: typeof ServeServantLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve/give': {
      id: '/serve/give'
      path: '/serve/give'
      fullPath: '/serve/give'
      preLoaderRoute: typeof ServeGiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$slug': {
      id: '/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/preview/$slug'
      preLoaderRoute: typeof PreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-steps/spiritual-retreat': {
      id: '/next-steps/spiritual-retreat'
      path: '/next-steps/spiritual-retreat'
      fullPath: '/next-steps/spiritual-retreat'
      preLoaderRoute: typeof NextStepsSpiritualRetreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-steps/small-groups': {
      id: '/next-steps/small-groups'
      path: '/next-steps/small-groups'
      fullPath: '/next-steps/small-groups'
      preLoaderRoute: typeof NextStepsSmallGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-steps/other-projects': {
      id: '/next-steps/other-projects'
      path: '/next-steps/other-projects'
      fullPath: '/next-steps/other-projects'
      preLoaderRoute: typeof NextStepsOtherProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-steps/ask': {
      id: '/next-steps/ask'
      path: '/next-steps/ask'
      fullPath: '/next-steps/ask'
      preLoaderRoute: typeof NextStepsAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-journey/my-story': {
      id: '/my-journey/my-story'
      path: '/my-journey/my-story'
      fullPath: '/my-journey/my-story'
      preLoaderRoute: typeof MyJourneyMyStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-journey/my-guru': {
      id: '/my-journey/my-guru'
      path: '/my-journey/my-guru'
      fullPath: '/my-journey/my-guru'
      preLoaderRoute: typeof MyJourneyMyGuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wisdom/blog2/': {
      id: '/wisdom/blog2/'
      path: '/wisdom/blog2'
      fullPath: '/wisdom/blog2/'
      preLoaderRoute: typeof WisdomBlog2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom/blog1/': {
      id: '/wisdom/blog1/'
      path: '/wisdom/blog1'
      fullPath: '/wisdom/blog1/'
      preLoaderRoute: typeof WisdomBlog1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom/blog/': {
      id: '/wisdom/blog/'
      path: '/wisdom/blog'
      fullPath: '/wisdom/blog/'
      preLoaderRoute: typeof WisdomBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom/blog2/$slug': {
      id: '/wisdom/blog2/$slug'
      path: '/wisdom/blog2/$slug'
      fullPath: '/wisdom/blog2/$slug'
      preLoaderRoute: typeof WisdomBlog2SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom/blog1/$slug': {
      id: '/wisdom/blog1/$slug'
      path: '/wisdom/blog1/$slug'
      fullPath: '/wisdom/blog1/$slug'
      preLoaderRoute: typeof WisdomBlog1SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom/blog/$slug': {
      id: '/wisdom/blog/$slug'
      path: '/wisdom/blog/$slug'
      fullPath: '/wisdom/blog/$slug'
      preLoaderRoute: typeof WisdomBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design/$id': {
      id: '/admin/design/$id'
      path: '/design/$id'
      fullPath: '/admin/design/$id'
      preLoaderRoute: typeof AdminDesignIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDesignIdRoute: typeof AdminDesignIdRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDesignIdRoute: AdminDesignIdRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  HomeRoute: HomeRoute,
  NewsletterRoute: NewsletterRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SurpriseRoute: SurpriseRoute,
  MyJourneyMyGuruRoute: MyJourneyMyGuruRoute,
  MyJourneyMyStoryRoute: MyJourneyMyStoryRoute,
  NextStepsAskRoute: NextStepsAskRoute,
  NextStepsOtherProjectsRoute: NextStepsOtherProjectsRoute,
  NextStepsSmallGroupsRoute: NextStepsSmallGroupsRoute,
  NextStepsSpiritualRetreatRoute: NextStepsSpiritualRetreatRoute,
  PostSlugRoute: PostSlugRoute,
  PreviewSlugRoute: PreviewSlugRoute,
  ServeGiveRoute: ServeGiveRoute,
  ServeServantLeadersRoute: ServeServantLeadersRoute,
  ServeTransformationalStoriesRoute: ServeTransformationalStoriesRoute,
  ServeVolunteerRoute: ServeVolunteerRoute,
  TagSlugRoute: TagSlugRoute,
  WisdomAudioPlaylistsRoute: WisdomAudioPlaylistsRoute,
  WisdomLordRoute: WisdomLordRoute,
  MyJourneyIndexRoute: MyJourneyIndexRoute,
  NextStepsIndexRoute: NextStepsIndexRoute,
  ServeIndexRoute: ServeIndexRoute,
  WisdomIndexRoute: WisdomIndexRoute,
  WisdomBlogSlugRoute: WisdomBlogSlugRoute,
  WisdomBlog1SlugRoute: WisdomBlog1SlugRoute,
  WisdomBlog2SlugRoute: WisdomBlog2SlugRoute,
  WisdomBlogIndexRoute: WisdomBlogIndexRoute,
  WisdomBlog1IndexRoute: WisdomBlog1IndexRoute,
  WisdomBlog2IndexRoute: WisdomBlog2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
