/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MyStoryRouteImport } from './routes/my-story'
import { Route as MyGuruRouteImport } from './routes/my-guru'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as PreviewSlugRouteImport } from './routes/preview.$slug'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'
import { Route as AdminDesignIdRouteImport } from './routes/admin.design.$id'

const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStoryRoute = MyStoryRouteImport.update({
  id: '/my-story',
  path: '/my-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGuruRoute = MyGuruRouteImport.update({
  id: '/my-guru',
  path: '/my-guru',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSlugRoute = PreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignIdRoute = AdminDesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/my-guru': typeof MyGuruRoute
  '/my-story': typeof MyStoryRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/surprise': typeof SurpriseRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/post/$slug': typeof PostSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/design/$id': typeof AdminDesignIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/my-guru': typeof MyGuruRoute
  '/my-story': typeof MyStoryRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/surprise': typeof SurpriseRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/post/$slug': typeof PostSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/design/$id': typeof AdminDesignIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/my-guru': typeof MyGuruRoute
  '/my-story': typeof MyStoryRoute
  '/newsletter': typeof NewsletterRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/surprise': typeof SurpriseRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/setup': typeof AdminSetupRoute
  '/post/$slug': typeof PostSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/design/$id': typeof AdminDesignIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/my-guru'
    | '/my-story'
    | '/newsletter'
    | '/rss.xml'
    | '/surprise'
    | '/admin/login'
    | '/admin/new'
    | '/admin/setup'
    | '/post/$slug'
    | '/preview/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/admin/design/$id'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/contact'
    | '/my-guru'
    | '/my-story'
    | '/newsletter'
    | '/rss.xml'
    | '/surprise'
    | '/admin/login'
    | '/admin/new'
    | '/admin/setup'
    | '/post/$slug'
    | '/preview/$slug'
    | '/tag/$slug'
    | '/admin'
    | '/admin/design/$id'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/my-guru'
    | '/my-story'
    | '/newsletter'
    | '/rss.xml'
    | '/surprise'
    | '/admin/login'
    | '/admin/new'
    | '/admin/setup'
    | '/post/$slug'
    | '/preview/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/admin/design/$id'
    | '/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  MyGuruRoute: typeof MyGuruRoute
  MyStoryRoute: typeof MyStoryRoute
  NewsletterRoute: typeof NewsletterRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SurpriseRoute: typeof SurpriseRoute
  PostSlugRoute: typeof PostSlugRoute
  PreviewSlugRoute: typeof PreviewSlugRoute
  TagSlugRoute: typeof TagSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-story': {
      id: '/my-story'
      path: '/my-story'
      fullPath: '/my-story'
      preLoaderRoute: typeof MyStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-guru': {
      id: '/my-guru'
      path: '/my-guru'
      fullPath: '/my-guru'
      preLoaderRoute: typeof MyGuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$slug': {
      id: '/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/preview/$slug'
      preLoaderRoute: typeof PreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design/$id': {
      id: '/admin/design/$id'
      path: '/design/$id'
      fullPath: '/admin/design/$id'
      preLoaderRoute: typeof AdminDesignIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDesignIdRoute: typeof AdminDesignIdRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDesignIdRoute: AdminDesignIdRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  MyGuruRoute: MyGuruRoute,
  MyStoryRoute: MyStoryRoute,
  NewsletterRoute: NewsletterRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SurpriseRoute: SurpriseRoute,
  PostSlugRoute: PostSlugRoute,
  PreviewSlugRoute: PreviewSlugRoute,
  TagSlugRoute: TagSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
